#!/bin/bash

cp /etc/collectd/configs/collectd.$CONFIG_TYPE.conf.tpl /etc/collectd/collectd.conf.tpl
envtpl /etc/collectd/collectd.conf.tpl

for f in /etc/collectd/configs/collectd.conf.d/*.conf.tpl; do
    file=${f##*/}
    cp $f /etc/collectd/collectd.conf.d/${file}
    envtpl /etc/collectd/collectd.conf.d/${file}
done

collectd -f
